# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Test
tagline:          Test
url:              http://leagueofwashu.github.io
paginate:         3
baseurl:          http://leagueofwashu.github.io
author:
  name:           Brian Choi
  url:            
  email:          

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
pages_list:
  Archives:	  '/archives'
