# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            League of WashU
tagline:          The official League of Legends and eSports club at Washington University in St. Louis
url:              http://low.wustl.edu
paginate:         3
baseurl:          http://low.wustl.edu
author:
  name:           Brian Choi
  url:            
  email:          brian.choi@wustl.edu

# Custom vars
version:          1.0.0
